#!/bin/bash
set -ex

DELAY=${DELAY:-5}
SOURCE_DIR=${SOURCE_DIR:-}
SOURCE_USER=${SOURCE_USER:-root}
SOURCE_GROUP=${SOURCE_GROUP:-root}
SOURCE_PERM=${SOURCE_PERM:-755}
TARGET_DIR=${TARGET_DIR:-}
TARGET_HOST=${TARGET_HOST:-}
SOURCE_PORT=${SOURCE_PORT:-22}
TARGET_PORT=${TARGET_PORT:-22}

if [ -z "${SOURCE_DIR}" ] ; then
    echo "ERROR: "
    echo " Please specify source dir."
    echo " You can do this by '-e SOURCE_DIR=/SOURCE/PATH/'."
    exit 1
fi

if [ -z "${TARGET_DIR}" ] ; then
    echo "ERROR: "
    echo " Please specify target dir."
    echo " You can do this by '-e TARGET_DIR=/TARGET/PATH/'."
    exit 1
fi

add_end_slash() {
    if [ -z "$(echo "$1" | egrep "/$")" ] ; then
        echo "$1/"
    else
        echo "$1"
    fi
}

SOURCE_DIR="$(add_end_slash "${SOURCE_DIR}")"
TARGET_DIR="$(add_end_slash "${TARGET_DIR}")"

# Set the owner and permissions for the source volume
chown -R ${SOURCE_USER}:${SOURCE_GROUP} ${SOURCE_DIR}
chmod -R ${SOURCE_PERM} ${SOURCE_DIR}

# Replace the placeholders in config files with actual values
sed 's#{{DELAY}}#'"${DELAY}"'#' -i /app/config/lsyncd.conf
sed 's#{{SOURCE_DIR}}#'"${SOURCE_DIR}"'#' -i /app/config/lsyncd.conf
sed 's#{{TARGET_DIR}}#'"${TARGET_DIR}"'#' -i /app/config/lsyncd.conf
sed 's#{{TARGET_HOST}}#'"${TARGET_HOST}"'#' -i /app/config/lsyncd.conf
sed 's#{{SOURCE_PORT}}#'"${SOURCE_PORT}"'#' -i /etc/ssh/sshd_config

# Generate an ssh config file for connecting to the right port
cat - > /root/.ssh/config <<EOF
Host $TARGET_HOST
Port $TARGET_PORT
StrictHostKeyChecking no
EOF

# (Re)start sshd
service ssh restart

case "$1" in
    start)
        # The -insist parameter is needed as the other side may not be up yet
        lsyncd -log Exec /app/config/lsyncd.conf -insist
        ;;
    *)
        prog=$(which $1)

        # check if the program exists.
        [[ -n "${prog}" ]]   || { echo "Can't find command $1" ; exit 1 ; }

        # check fi the grogram can be excuted.
        [[ -x "${prog}" ]] || { echo "Can't execute cmd $1"  ; exit 1 ; }

        # run command with arguments.
        shift 1
        ${prog} $@
        ;;
esac
